// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: agent.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Progress / metadata updates
type Stage int32

const (
	Stage_tool_execution_starting     Stage = 0
	Stage_tool_execution_failed       Stage = 1
	Stage_tool_execution_completed    Stage = 2
	Stage_answer_generation_starting  Stage = 3
	Stage_answer_generation_failed    Stage = 4
	Stage_answer_generation_completed Stage = 5
)

// Enum value maps for Stage.
var (
	Stage_name = map[int32]string{
		0: "tool_execution_starting",
		1: "tool_execution_failed",
		2: "tool_execution_completed",
		3: "answer_generation_starting",
		4: "answer_generation_failed",
		5: "answer_generation_completed",
	}
	Stage_value = map[string]int32{
		"tool_execution_starting":     0,
		"tool_execution_failed":       1,
		"tool_execution_completed":    2,
		"answer_generation_starting":  3,
		"answer_generation_failed":    4,
		"answer_generation_completed": 5,
	}
)

func (x Stage) Enum() *Stage {
	p := new(Stage)
	*p = x
	return p
}

func (x Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (Stage) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stage.Descriptor instead.
func (Stage) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type GenerateAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	MaxIterations int32                  `protobuf:"varint,3,opt,name=maxIterations,proto3" json:"maxIterations,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateAnswerRequest) Reset() {
	*x = GenerateAnswerRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAnswerRequest) ProtoMessage() {}

func (x *GenerateAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAnswerRequest.ProtoReflect.Descriptor instead.
func (*GenerateAnswerRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateAnswerRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *GenerateAnswerRequest) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *GenerateAnswerRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AgentStreamChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ChunkType:
	//
	//	*AgentStreamChunk_ProgressUpdateChunk
	//	*AgentStreamChunk_ToolResultChunk
	//	*AgentStreamChunk_Answer
	//	*AgentStreamChunk_Complete
	//	*AgentStreamChunk_Error
	ChunkType     isAgentStreamChunk_ChunkType `protobuf_oneof:"chunk_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStreamChunk) Reset() {
	*x = AgentStreamChunk{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStreamChunk) ProtoMessage() {}

func (x *AgentStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStreamChunk.ProtoReflect.Descriptor instead.
func (*AgentStreamChunk) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentStreamChunk) GetChunkType() isAgentStreamChunk_ChunkType {
	if x != nil {
		return x.ChunkType
	}
	return nil
}

func (x *AgentStreamChunk) GetProgressUpdateChunk() *ProgressUpdateChunk {
	if x != nil {
		if x, ok := x.ChunkType.(*AgentStreamChunk_ProgressUpdateChunk); ok {
			return x.ProgressUpdateChunk
		}
	}
	return nil
}

func (x *AgentStreamChunk) GetToolResultChunk() *ToolResultChunk {
	if x != nil {
		if x, ok := x.ChunkType.(*AgentStreamChunk_ToolResultChunk); ok {
			return x.ToolResultChunk
		}
	}
	return nil
}

func (x *AgentStreamChunk) GetAnswer() *AnswerChunk {
	if x != nil {
		if x, ok := x.ChunkType.(*AgentStreamChunk_Answer); ok {
			return x.Answer
		}
	}
	return nil
}

func (x *AgentStreamChunk) GetComplete() *StreamComplete {
	if x != nil {
		if x, ok := x.ChunkType.(*AgentStreamChunk_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *AgentStreamChunk) GetError() *StreamError {
	if x != nil {
		if x, ok := x.ChunkType.(*AgentStreamChunk_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isAgentStreamChunk_ChunkType interface {
	isAgentStreamChunk_ChunkType()
}

type AgentStreamChunk_ProgressUpdateChunk struct {
	ProgressUpdateChunk *ProgressUpdateChunk `protobuf:"bytes,1,opt,name=progressUpdateChunk,proto3,oneof"`
}

type AgentStreamChunk_ToolResultChunk struct {
	ToolResultChunk *ToolResultChunk `protobuf:"bytes,3,opt,name=toolResultChunk,proto3,oneof"`
}

type AgentStreamChunk_Answer struct {
	Answer *AnswerChunk `protobuf:"bytes,4,opt,name=answer,proto3,oneof"`
}

type AgentStreamChunk_Complete struct {
	Complete *StreamComplete `protobuf:"bytes,5,opt,name=complete,proto3,oneof"`
}

type AgentStreamChunk_Error struct {
	Error *StreamError `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

func (*AgentStreamChunk_ProgressUpdateChunk) isAgentStreamChunk_ChunkType() {}

func (*AgentStreamChunk_ToolResultChunk) isAgentStreamChunk_ChunkType() {}

func (*AgentStreamChunk_Answer) isAgentStreamChunk_ChunkType() {}

func (*AgentStreamChunk_Complete) isAgentStreamChunk_ChunkType() {}

func (*AgentStreamChunk_Error) isAgentStreamChunk_ChunkType() {}

type ProgressUpdateChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Stage          Stage                  `protobuf:"varint,1,opt,name=stage,proto3,enum=agent.Stage" json:"stage,omitempty"`
	Timestamp      int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EstimatedSteps int32                  `protobuf:"varint,5,opt,name=estimatedSteps,proto3" json:"estimatedSteps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProgressUpdateChunk) Reset() {
	*x = ProgressUpdateChunk{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdateChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdateChunk) ProtoMessage() {}

func (x *ProgressUpdateChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdateChunk.ProtoReflect.Descriptor instead.
func (*ProgressUpdateChunk) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ProgressUpdateChunk) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_tool_execution_starting
}

func (x *ProgressUpdateChunk) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProgressUpdateChunk) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressUpdateChunk) GetEstimatedSteps() int32 {
	if x != nil {
		return x.EstimatedSteps
	}
	return 0
}

// Raw result chunk of a single tool.
// A single tool can emit multiple ToolExecutionResultChunk.
type ToolResultChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sentences     []string               `protobuf:"bytes,1,rep,name=sentences,proto3" json:"sentences,omitempty"`
	Attribution   string                 `protobuf:"bytes,2,opt,name=attribution,proto3" json:"attribution,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ToolName      string                 `protobuf:"bytes,5,opt,name=toolName,proto3" json:"toolName,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Id            string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultChunk) Reset() {
	*x = ToolResultChunk{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultChunk) ProtoMessage() {}

func (x *ToolResultChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultChunk.ProtoReflect.Descriptor instead.
func (*ToolResultChunk) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ToolResultChunk) GetSentences() []string {
	if x != nil {
		return x.Sentences
	}
	return nil
}

func (x *ToolResultChunk) GetAttribution() string {
	if x != nil {
		return x.Attribution
	}
	return ""
}

func (x *ToolResultChunk) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ToolResultChunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ToolResultChunk) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolResultChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolResultChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Final Answer Chunk
type AnswerChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerChunk) Reset() {
	*x = AnswerChunk{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerChunk) ProtoMessage() {}

func (x *AnswerChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerChunk.ProtoReflect.Descriptor instead.
func (*AnswerChunk) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AnswerChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// End of Streaming.
type StreamComplete struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FinalStatus    string                 `protobuf:"bytes,1,opt,name=final_status,json=finalStatus,proto3" json:"final_status,omitempty"`
	Answer         string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	TokenUsed      int32                  `protobuf:"varint,3,opt,name=tokenUsed,proto3" json:"tokenUsed,omitempty"`
	ProcessingTime int64                  `protobuf:"varint,4,opt,name=processingTime,proto3" json:"processingTime,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ToolsUsed      []string               `protobuf:"bytes,6,rep,name=toolsUsed,proto3" json:"toolsUsed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamComplete) Reset() {
	*x = StreamComplete{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamComplete) ProtoMessage() {}

func (x *StreamComplete) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamComplete.ProtoReflect.Descriptor instead.
func (*StreamComplete) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *StreamComplete) GetFinalStatus() string {
	if x != nil {
		return x.FinalStatus
	}
	return ""
}

func (x *StreamComplete) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *StreamComplete) GetTokenUsed() int32 {
	if x != nil {
		return x.TokenUsed
	}
	return 0
}

func (x *StreamComplete) GetProcessingTime() int64 {
	if x != nil {
		return x.ProcessingTime
	}
	return 0
}

func (x *StreamComplete) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StreamComplete) GetToolsUsed() []string {
	if x != nil {
		return x.ToolsUsed
	}
	return nil
}

// Error chunk
type StreamError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StreamError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StreamError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"\xde\x01\n" +
	"\x15GenerateAnswerRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12$\n" +
	"\rmaxIterations\x18\x03 \x01(\x05R\rmaxIterations\x12F\n" +
	"\bmetadata\x18\x04 \x03(\v2*.agent.GenerateAnswerRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x02\n" +
	"\x10AgentStreamChunk\x12N\n" +
	"\x13progressUpdateChunk\x18\x01 \x01(\v2\x1a.agent.ProgressUpdateChunkH\x00R\x13progressUpdateChunk\x12B\n" +
	"\x0ftoolResultChunk\x18\x03 \x01(\v2\x16.agent.ToolResultChunkH\x00R\x0ftoolResultChunk\x12,\n" +
	"\x06answer\x18\x04 \x01(\v2\x12.agent.AnswerChunkH\x00R\x06answer\x123\n" +
	"\bcomplete\x18\x05 \x01(\v2\x15.agent.StreamCompleteH\x00R\bcomplete\x12*\n" +
	"\x05error\x18\x06 \x01(\v2\x12.agent.StreamErrorH\x00R\x05errorB\f\n" +
	"\n" +
	"chunk_type\"\x99\x01\n" +
	"\x13ProgressUpdateChunk\x12\"\n" +
	"\x05stage\x18\x01 \x01(\x0e2\f.agent.StageR\x05stage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12&\n" +
	"\x0eestimatedSteps\x18\x05 \x01(\x05R\x0eestimatedSteps\"\xa8\x02\n" +
	"\x0fToolResultChunk\x12\x1c\n" +
	"\tsentences\x18\x01 \x03(\tR\tsentences\x12 \n" +
	"\vattribution\x18\x02 \x01(\tR\vattribution\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12@\n" +
	"\bmetadata\x18\x04 \x03(\v2$.agent.ToolResultChunk.MetadataEntryR\bmetadata\x12\x1a\n" +
	"\btoolName\x18\x05 \x01(\tR\btoolName\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\vAnswerChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\xad\x02\n" +
	"\x0eStreamComplete\x12!\n" +
	"\ffinal_status\x18\x01 \x01(\tR\vfinalStatus\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x1c\n" +
	"\ttokenUsed\x18\x03 \x01(\x05R\ttokenUsed\x12&\n" +
	"\x0eprocessingTime\x18\x04 \x01(\x03R\x0eprocessingTime\x12?\n" +
	"\bmetadata\x18\x05 \x03(\v2#.agent.StreamComplete.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttoolsUsed\x18\x06 \x03(\tR\ttoolsUsed\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\vStreamError\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode*\xbc\x01\n" +
	"\x05Stage\x12\x1b\n" +
	"\x17tool_execution_starting\x10\x00\x12\x19\n" +
	"\x15tool_execution_failed\x10\x01\x12\x1c\n" +
	"\x18tool_execution_completed\x10\x02\x12\x1e\n" +
	"\x1aanswer_generation_starting\x10\x03\x12\x1c\n" +
	"\x18answer_generation_failed\x10\x04\x12\x1f\n" +
	"\x1banswer_generation_completed\x10\x052M\n" +
	"\x05Agent\x12D\n" +
	"\aExecute\x12\x1c.agent.GenerateAnswerRequest\x1a\x17.agent.AgentStreamChunk\"\x000\x01B+Z)github.com/SaiNageswarS/agent-boot/schemab\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agent_proto_goTypes = []any{
	(Stage)(0),                    // 0: agent.Stage
	(*GenerateAnswerRequest)(nil), // 1: agent.GenerateAnswerRequest
	(*AgentStreamChunk)(nil),      // 2: agent.AgentStreamChunk
	(*ProgressUpdateChunk)(nil),   // 3: agent.ProgressUpdateChunk
	(*ToolResultChunk)(nil),       // 4: agent.ToolResultChunk
	(*AnswerChunk)(nil),           // 5: agent.AnswerChunk
	(*StreamComplete)(nil),        // 6: agent.StreamComplete
	(*StreamError)(nil),           // 7: agent.StreamError
	nil,                           // 8: agent.GenerateAnswerRequest.MetadataEntry
	nil,                           // 9: agent.ToolResultChunk.MetadataEntry
	nil,                           // 10: agent.StreamComplete.MetadataEntry
}
var file_agent_proto_depIdxs = []int32{
	8,  // 0: agent.GenerateAnswerRequest.metadata:type_name -> agent.GenerateAnswerRequest.MetadataEntry
	3,  // 1: agent.AgentStreamChunk.progressUpdateChunk:type_name -> agent.ProgressUpdateChunk
	4,  // 2: agent.AgentStreamChunk.toolResultChunk:type_name -> agent.ToolResultChunk
	5,  // 3: agent.AgentStreamChunk.answer:type_name -> agent.AnswerChunk
	6,  // 4: agent.AgentStreamChunk.complete:type_name -> agent.StreamComplete
	7,  // 5: agent.AgentStreamChunk.error:type_name -> agent.StreamError
	0,  // 6: agent.ProgressUpdateChunk.stage:type_name -> agent.Stage
	9,  // 7: agent.ToolResultChunk.metadata:type_name -> agent.ToolResultChunk.MetadataEntry
	10, // 8: agent.StreamComplete.metadata:type_name -> agent.StreamComplete.MetadataEntry
	1,  // 9: agent.Agent.Execute:input_type -> agent.GenerateAnswerRequest
	2,  // 10: agent.Agent.Execute:output_type -> agent.AgentStreamChunk
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentStreamChunk_ProgressUpdateChunk)(nil),
		(*AgentStreamChunk_ToolResultChunk)(nil),
		(*AgentStreamChunk_Answer)(nil),
		(*AgentStreamChunk_Complete)(nil),
		(*AgentStreamChunk_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
