name: agent-boot-relase

on:
  push:
    branches: [ main ]  # Trigger on main branch pushes
    tags: ['v*'] 
  workflow_dispatch:

jobs:
  build-search-core:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout API
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install protoc
        run: sudo apt install -y protobuf-compiler

      - name: Install go-grpc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest
          echo "${HOME}/go/bin" >> $GITHUB_PATH
          echo "Path is ${GITHUB_PATH}"

      - name: Build search-core 
        run: |
          cd proto 
          ./build.sh 
          cd ..
          cd search-core 
          ./build.sh 
          cd ..
          cd mcp-agent 
          ./build.sh 
          cd ..

      - name: Upload Go artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-binaries
          path: |
            search-core/build/*
            mcp-agent/build/*

  release:
    needs: [build-search-core]
    runs-on: ubuntu-latest

    steps:
    - name: Download Go artifacts
      uses: actions/download-artifact@v4
      with:
        name: go-binaries
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./artifacts/*
        body: |
          ## Downloads
          
          ### Go Executables
          - `search-core` - Search Service
          - `mcp-agent` - Linux mcp Executable
          - `mcp-agent.exe` - Windows mcp Executable

      


      

